version: "3.5"

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_redmine
    volumes:
      - database:/var/lib/postgresql/data
  frontend:
    image: frontend
    ports:
      - 5000:5000
    build: .
    container_name: frontend
  backend:
    image: backend
    environment:
      REDIS_HOST: http://localhost
      POSTGRES_HOST: http://localhost
      POSTGRES_PASSWORD: example
    ports:
      - 8080:8080
      # - 6379:6379
      # - 5432:5432
    build: .
    container_name: backend
  redis:
    image: redis
    # ports:
    #   - 6379:6379
    # build: .
    restart: unless-stopped 
    # command: redis-server --appendonly yes
    # command: ["redis-server", "--appendonly", "yes"]
    container_name: redis
  
volumes:
  database:

