version: "3.5"

services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
    build: .
    container_name: frontend
  backend:
    image: backend
    environment:
      - REDIS_HOST=redis 
    ports:
      - 8080:8080 
    build: .
    container_name: backend
  redis:
    image: redis 
    restart: unless-stopped  
    container_name: redis
