version: '3.5' 

services: 
    frontend:  
      image: frontend
      ports: 
        - 5000:5000
      build: .  
      container_name: frontend
    backend:  
      image: backend
      environment: 
        - REDIS_HOST=127.0.0.1:6379
      ports: 
        - 8080:8080
        - 6379:6379
      build: .  
      container_name: backend
    redis:
      image: redis 
      build: .  
      command: ["redis-server", "--appendonly", "yes"]    
      container_name: redis