version: "3.5"

services: 
  backend:
    image: kurkkumopo-backend 
    volumes:
        - model:/src/model
    ports:
      - 5000:5000
    container_name: backend 
  frontend:
    image: kurkkumopo-frontend
    ports:
      - 3000:3000
    container_name: frontend 
  training:
    image: kurkkumopo-training
    volumes:
      - model:/src/model
      - imgs:/src/imgs
    container_name: training 
volumes: 
    model:
    imgs:
    
 


   

