version: '3.5' 

services: 
    frontend:  
      image: frontend
      ports: 
        - 5000:5000
      build: .  
      container_name: frontend
    backend:  
      image: backend
      ports: 
        - 8080:8080
      build: .  
      container_name: backend