version: '3.5'
services:
  socket-io-server:
    build:
      context: ./socket-io-server 
    ports:
      - "4001:4001"
    container_name: socket-io-server
    volumes:
       - ./socket-io-server:/usr/src/app/server
       - node_modules_server:/usr/src/app/server/node_modules
  socket-io-client:
    build:
      context: ./socket-io-client 
    ports:
      - "3000:3000"
    container_name: socket-io-client
    stdin_open: true
    volumes:
       - ./socket-io-client:/usr/src/app/client
       - node_modules_client:/usr/src/app/client/node_modules
volumes:
    node_modules_server:
    node_modules_client: